#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# floating
floating="^(zoom|League of Legends|Riot Client|Cisco|FaceTime|Finder|System Settings|Preview|Activity Monitor|CrossOver|Risk of Rain 2|Anki|League|Blitz|Blender|napari)"
yabai -m rule --add app="$floating" manage=off sub-layer=normal
yabai -m rule --add app="^MATLAB" title="^Figure" manage=off sub-layer=normal
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --apply

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      1.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                off
yabai -m config window_border_hidpi          on
yabai -m config window_border_radius         11
yabai -m config window_border_blur           off
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff849ed1
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# stack vscode (space 5) and chat apps (space 6)
yabai -m space 5 --layout stack
yabai -m space 6 --layout stack

# focus previous window when window dies even if other instances exist
yabai -m signal --add event=window_destroyed app=".*" action="yabai -m window --focus \$(yabai -m query --windows --space | jq '.[0].id')"
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
yabai -m rule --apply

# added settings
echo "yabai configuration loaded.."
